dist: xenial
sudo: required
language: c

branches:
  only:
  - v8.8
  - v8.9
  - v8.9+worker
  - v8.10

cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    packages:
    - gcc-multilib
env:
  global:
  - NJOBS=2
  - OPAMROOTISOK="true"
  - OPAMYES="true"
  - OPAMJOBS="2"
  - COMPILER="4.07.1+32bit"
  - BASE_OPAM="num dune elpi.1.1.1"

before_install: |
  sudo curl -sL https://github.com/ocaml/opam/releases/download/2.0.1/opam-2.0.1-x86_64-linux -o /usr/bin/opam
  sudo chmod 755 /usr/bin/opam

install:
- opam init -c "$COMPILER" --disable-sandboxing
- opam switch set "$COMPILER"
- eval $(opam env)
- opam install $BASE_OPAM
- opam list
- opam update
- opam config var root
- ./etc/toolchain-setup.sh
- opam list
- git submodule update --remote

script:
- set -e
- echo 'Building Coq...' && echo -en 'travis_fold:start:coq.build\\r'
- make coq-get
- echo -en 'travis_fold:end:coq.build\\r'
- echo 'Building JsCoq...' && echo -en 'travis_fold:start:jscoq.build\\r'
- make jscoq
- make libs-pkg
- echo -en 'travis_fold:end:jscoq.build\\r'
- echo 'Building Addons...' && echo -en 'travis_fold:start:addons.build\\r'
- make addons
- make jscoq
- make libs-pkg
- echo -en 'travis_fold:end:addons.build\\r'
