language: node_js

node_js:
- "8"

matrix:
  include:
  - os: linux
    env: JSCOQ_ARCH=32
  - os: osx
    env: JSCOQ_ARCH=64

branches:
  only:
  - v8.8
  - v8.9
  - v8.9+worker
  - v8.10
  - v8.11

addons:
  apt:
    packages:
    - gcc-multilib
  homebrew:
    update: true
    packages:
    - opam

cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/Library/Caches/Homebrew

env:
  global:
  - NJOBS="2"
  - OPAMROOTISOK="true"
  - OPAMYES="true"
  - OPAMJOBS="2"
  - OPAM_LINUX_URL=https://github.com/ocaml/opam/releases/download/2.0.4/opam-2.0.4-x86_64-linux

before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    sudo curl -sL $OPAM_LINUX_URL -o /usr/bin/opam &&
    sudo chmod 755 /usr/bin/opam; fi

before_cache:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cleanup; fi

install:
- opam init -y --bare --disable-sandboxing || true
- eval $(opam env)
- ./etc/toolchain-setup.sh --"$JSCOQ_ARCH"
- eval $(opam env)
- opam switch
- opam list
- opam config var root
- git submodule update --remote

script:
- echo 'Using Node.js:' && node --version
- set -e
- echo 'Building Coq...' && echo -en 'travis_fold:start:coq.build\\r'
- make coq-get
- echo -en 'travis_fold:end:coq.build\\r'
- echo 'Building JsCoq...' && echo -en 'travis_fold:start:jscoq.build\\r'
- make jscoq
- make libs-pkg
- echo -en 'travis_fold:end:jscoq.build\\r'
- echo 'Building Addons...' && echo -en 'travis_fold:start:addons.build\\r'
- make addons
- make jscoq
- make libs-pkg
- echo -en 'travis_fold:end:addons.build\\r'
